### ISSUE TITLE
saving SOLEs is not working (impersonating undefined error)

### ISSUE THREAD

**Issue by jsduffy** [startsole/startsole2#101]
4|sole     | 2018.07.18 19:26:32.367 [23243] - error: cloudCall #24: (a4c8...59e4) webapp.addSole FATAL ERROR => TypeError: Cannot read property 'impersonate' of undefinedTypeError: Cannot read property 'impersonate' of undefined
4|sole     |     at Sole.Parse.Object.extend.Parse.Object.setValue (/home/parse/sole/cloud/Model/DataPointValue.js:741:21)
4|sole     |     at Function.addSole (/home/parse/sole/cloud/Controllers/Webapp.js:441:14)
4|sole     |     at ParsePromise.session.loadUser.then.then._ (/home/parse/sole/cloud/soleapp.js:333:59)
4|sole     |     at ParsePromise.wrappedResolvedCallback (/usr/lib/node_modules/parse/lib/node/ParsePromise.js:152:43)
4|sole     |     at ParsePromise.value (/usr/lib/node_modules/parse/lib/node/ParsePromise.js:90:36)
4|sole     |     at ParsePromise.<anonymous> (/usr/lib/node_modules/parse/lib/node/ParsePromise.js:162:29)
4|sole     |     at ParsePromise.wrappedResolvedCallback (/usr/lib/node_modules/parse/lib/node/ParsePromise.js:152:43)
4|sole     |     at /usr/lib/node_modules/parse/lib/node/ParsePromise.js:218:35
4|sole     |     at process._tickCallback (internal/process/next_tick.js:150:11)
24|webapp  | error saving sole ParseError { code: 141, message: 'fatal error' }
3|sole     | 2018.07.18 19:26:55.541 [23236] - info: CloudCall #15: (unde...ined) webapp.getAllMyQuestions(offset:"0", limit:"100")
24|webapp  | error getting all questions! ParseError {
24|webapp  |   code: 107,
24|webapp  |   message: 'Received an error with invalid JSON from Parse: <html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body bgcolor="white">\r\n<center><h1>504 Gateway Time-out</h1></center>\r\n<hr><center>nginx/1.4.6 (Ubuntu)</center>\r\n</body>\r\n</html>\r\n' }

**Comment by drewrwilson** [comment]
I think this is fixed. I'm pushing to staging now
