### ISSUE TITLE
Updating a SOLE and changing it's question doesn't work.

### ISSUE THREAD

**Issue by jsduffy** [startsole/startsole2#111]
Other fields seem to update properly, but changing the question text doesn't save a new question

**Comment by drewrwilson** [comment]
Just so I'm understanding correctly, is this the intended behavior here?

when a user updates the question on an existing lesson plan, the backend makes a new question and new question ID and associates it with the lesson plan.

**Comment by jsduffy** [comment]
This seems to be all set.  May have just been hanging chad

![hangint](https://twt-thumbs.washtimes.com/media/image/2012/09/23/20120923-171949-pic-224799225_s1646x2048.jpg?cfbd5dd6d6a84301da70a13921990d699ec8c5ab "Chad")
