### ISSUE TITLE
Force lowercase for email address on signup/register

### ISSUE THREAD

**Issue by jsduffy** [startsole/startsole2#124]
When a user signs up for a new account or logs in using email/password, force the email value to be sent to Parse as a lowercase string.  If the lowercase login fails, another attempt to login could be made with the original string (this shouldn't be necessary but may be a good redundant check).

Jsduffy@gmail.com
password

Try to log in as jsduffy@gmail.com, if that fails then try Jsduffy@gmail.com

**Comment by drewrwilson** [comment]
on it

**Comment by drewrwilson** [comment]
reopening because I didn't make the fallback option

**Comment by drewrwilson** [comment]
300fdb39
