### ISSUE TITLE
Display points and CEUs on profile page

### ISSUE THREAD

**Issue by drewrwilson** [startsole/startsole2#77]
add something to cloud code to get it
pass it to the controller
pass it to the view
pass it to the view controller
pass it back to the view
display it
update it with jquery
repeat

**Comment by drewrwilson** [comment]
add profile pic

**Comment by drewrwilson** [comment]
and completed tutorials

**Comment by drewrwilson** [comment]
and a header  image

**Comment by drewrwilson** [comment]
and a siq background

**Comment by drewrwilson** [comment]
and their star sign

**Comment by drewrwilson** [comment]
(and a twitter feed)

**Comment by drewrwilson** [comment]
pivot: now this is an app about stars

**Comment by drewrwilson** [comment]
can we add a DPV for stars? like not specifically stars, like  maybe the  DPV is heavenly bodies and  "star" is property in the pointer?

**Comment by drewrwilson** [comment]
nevermind, it's all just Data

**Comment by jsduffy** [comment]
typical Virgo
