### ISSUE TITLE
Add ability for a user to set their location when they sign up

### ISSUE THREAD

**Issue by drewrwilson** [startsole/startsole2#79]
Set their school and location and all that stuff

**Comment by drewrwilson** [comment]
Current status: data comes from the frontend, through the controllers to the cloud code. But it does not yet save to the database

**Comment by jsduffy** [comment]
This is almost done now, we just need to disable the form submit when you hit enter on the school selection

**Comment by drewrwilson** [comment]
done! 🇵🇷
